/**
 * Static astronomy data types for AstroPilot.
 * Data files live next to this file (see shared/data/README.md for sources & licenses).
 * Generated by scripts/data/build-catalog.mjs and scripts/data/build-sky.mjs — do not edit the JSON by hand.
 */

/** Object classification used by catalog.json. */
export type ObjectType =
  | 'galaxy' | 'galaxy_group' | 'open_cluster' | 'globular_cluster' | 'cluster_nebula'
  | 'planetary_nebula' | 'emission_nebula' | 'reflection_nebula' | 'dark_nebula'
  | 'supernova_remnant' | 'double_star' | 'asterism' | 'star_cloud';

/** One entry of shared/data/catalog.json (all coordinates J2000, epoch 2000.0). */
export interface CatalogObject {
  /** URL-safe canonical id: "M31", "NGC7000", "IC434", "C41" (only for Caldwell objects with no NGC/IC number), doubles as slugs like "albireo", "epsilon-lyrae" */
  id: string;
  /** Display name: common name if any ("Andromeda Galaxy"), else designation with a space ("NGC 7331") */
  name: string;
  /** All display designations for search, e.g. ["M 31","NGC 224","Andromeda Galaxy"]; includes Caldwell as "C 14" */
  designations: string[];
  /** Messier number */
  m?: number;
  /** Caldwell number */
  c?: number;
  type: ObjectType;
  /** J2000 right ascension in decimal HOURS (0..24), 4 decimals */
  ra: number;
  /** J2000 declination in decimal degrees, 3 decimals */
  dec: number;
  /**
   * Visual (V) magnitude; falls back to B when no usable V exists (then `magB` is true).
   * For double stars this is the primary's magnitude (WDS).
   */
  mag?: number;
  /** true when `mag` is a B (blue) magnitude */
  magB?: boolean;
  /**
   * Set when `mag` is not the brightness of the nebulosity itself: "star" = the illuminating star's magnitude
   * (e.g. IC 4604, NGC 7023), "cluster" = the embedded star cluster's (every cluster_nebula except M42, e.g. M16).
   * The nebula is much fainter than such a magnitude suggests.
   */
  magOf?: 'star' | 'cluster';
  /**
   * Major (and minor) axis in arcminutes: the commonly quoted visual dimensions (SEDS for Messier objects,
   * Wikipedia / NGC 2000.0 / OpenNGC otherwise; galaxies use isophotal D25 diameters — see README).
   */
  size?: [number, number] | [number];
  /**
   * Surface brightness in mag/arcmin² (galaxies only). Derived from OpenNGC SurfBr — the mean
   * B-band surface brightness within the 25 mag/arcsec² isophote, published in mag/arcsec² —
   * converted with sb = SurfBr − 2.5·log10(3600) (≈ −8.89).
   */
  sb?: number;
  /** IAU constellation 3-letter abbreviation, e.g. "And" (Serpens is always "Ser") */
  con: string;
  /** Galaxy morphology from OpenNGC (e.g. "SBb", "E", "S0-a") */
  hubble?: string;
  /** Double stars: separation in arcseconds (current epoch, see README) */
  sep?: number;
  /** Double stars: companion magnitude */
  mag2?: number;
  /**
   * Position angle in whole degrees, measured from north through east. Double stars: direction of the companion
   * from the primary (0–359). Extended objects: orientation of the major axis (0–179; only for elongated objects
   * with both axes in `size`, from OpenNGC).
   */
  pa?: number;
  /** 1-3 sentence plain-language description */
  desc?: string;
  /** A "wow" object for beginners and outreach */
  showpiece?: boolean;
}

/**
 * shared/data/stars.json is a flat array of tuples, brightest first:
 *   [raHours, decDeg, mag, bv]   (3 / 3 / 2 / 2 decimals; J2000)
 * `bv` (B−V colour index) is omitted — i.e. the tuple has 3 elements — when the source has no value.
 */
export interface StarRecord { /* tuple encoded in stars.json */ }
